{'Package': 'python3-requestsexceptions', 'Source': 'python-requestsexceptions', 'Version': '1.4.0-1', 'Installed-Size': '23', 'Maintainer': 'Debian OpenStack <team+openstack@tracker.debian.org>', 'Architecture': 'all', 'Depends': [['python3-pbr', '>=', '2.0.0'], ['python3-urllib3', '>=', '1.13'], 'python3:any'], 'Description': 'import exceptions from bundled packages in requests. - Python 3.x', 'Homepage': 'http://www.openstack.org/', 'Description-md5': '69eb6ceafcc256efdfb4eb0d4dce11c3', 'Section': 'python', 'Priority': 'extra', 'Filename': 'pool/main/p/python-requestsexceptions/python3-requestsexceptions_1.4.0-1_all.deb', 'Size': '4140', 'SHA256': '724a312468ec4d0a4f844de7f32310c2fc923b7e51249aa45bc797da88ed944d'}