{'Package': 'python-requestsexceptions', 'Version': '1.4.0-1', 'Installed-Size': '23', 'Maintainer': 'Debian OpenStack <team+openstack@tracker.debian.org>', 'Architecture': 'all', 'Depends': [['python-pbr', '>=', '2.0.0'], ['python-urllib3', '>=', '1.13'], ['python:any', '<<', '2.8'], ['python:any', '>=', '2.7~']], 'Description': 'import exceptions from bundled packages in requests. - Python 2.7', 'Homepage': 'http://www.openstack.org/', 'Description-md5': '4d938c7960c4fdff8fd8bf6b6d2578cb', 'Section': 'python', 'Priority': 'extra', 'Filename': 'pool/main/p/python-requestsexceptions/python-requestsexceptions_1.4.0-1_all.deb', 'Size': '4056', 'SHA256': '329bb0d1eaab69117fd8573c63be71aebd6dcbff221180c85f3d540eb4d3408f'}